### ISSUE TITLE
Make `Fs.Constants` abstract?

### ISSUE THREAD

**Issue by yawaramin** [sikanhe/reason-node#34]
Currently, the Node `fs` module constants are bound as `int`: https://github.com/sikanhe/reason-nodejs/blob/a4fc5e9016d7fb22f79cd118c834ec19f25b604d/src/Fs.re#L75

But in the [Node `fs` docs](https://nodejs.org/dist/latest-v10.x/docs/api/fs.html#fs_fs_constants_1), it's never specified that they are numbers. So I'm wondering if you would be open to making the constants bindings an abstract type, e.g.

```reason
module Constants = {
  type t;

  [@bs.module "fs"] [@bs.scope "constants"] external f_ok: t = "F_OK";
};
```

And so on. I can also add the rest of the constants in the module.

**Comment by austindd** [comment]
Yeah, you're totally right. I think that's the right call. I want to say we inspected the values at runtime to see what they were under the hood, but it's probably irrelevant. Abstract types make sense.

**Comment by yawaramin** [comment]
Thanks Austin. I just realized that these constants are expected to be used as ints, e.g. from https://nodejs.org/dist/latest-v10.x/docs/api/fs.html#fs_fs_copyfile_src_dest_flags_callback:

> `flags` is an optional integer that specifies the behavior of the copy operation. It is possible to create a mask consisting of the bitwise OR of two or more values (e.g.` fs.constants.COPYFILE_EXCL | fs.constants.COPYFILE_FICLONE`).

So the type of all flags would also need to be changed to `Constants.t` and also a logical-or operator (or function) would need to be added to allow doing bitmasks. But that is reasonably easy, e.g.

```reason
module Constants: {
  type t;
  ...
  let (||): (t, t) => t;
} = {
  type t = int;
  ...
  let (||)(t1, t2) = t1 lor t2;
};
```

**Comment by austindd** [comment]
On the other hand, if the constants are each instances of separate abstract types, then it's tricky to pattern match on them. And I can imagine use cases for pattern matching. What do you think?

**Comment by yawaramin** [comment]
Yeah you're right, that can also be solved by using a `pri int` type, since the docs do implicitly say that it should be an `int`.

**Comment by austindd** [comment]
Right, I see what you mean about the flags. And the `pri` type makes sense. If you want to make a PR I’ll be happy to review/merge it.

**Comment by yawaramin** [comment]
Sure, I'll send a PR soon.
