### ISSUE TITLE
Examples should show namespace

### ISSUE THREAD

**Issue by varnerac** [sikanhe/reason-node#43]
For newcomers like myself, it'd be nice for the examples to show that the library modules should be called with the `NodeJS` namespace, like:

```
NodeJs.Fs.access("foo")
```

The examples leave the namespace out.

**Comment by austindd** [comment]
@varnerac Thanks for the feedback. We will likely change this soon. I agree the omission of the module is confusing.

**Comment by wontheone1** [comment]
Just stumbled upon the same problem with the author of this issue. I got help from Discord.

**Comment by TheSpyder** [comment]
I've included this change in TheSpyder/rescript-nodejs#1 (I just published v14)
